version: '3.8'

services:
  python:
    container_name: 'main-project-python'
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    command: bash -c "cd ui && npm run serve"
    volumes:
      - ./server:/srv
    ports:
      - 8000:5000
      - 8001:8080
    depends_on:
      - db
    networks:
      - network

  db:
    container_name: 'main-project-db'
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - .database:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - network

  phpmyadmin:
    container_name: 'main-project-phpmyadmin'
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=main-project-db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    ports:
      - 8080:80
    networks:
      - network

networks:
  network:
