version: '3.8'

services:
  server:
    container_name: 'main-project-nginx'
    image: nginx:1.15
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/var/www/html
    depends_on:
      - flask
    networks:
      - network
  flask:
    container_name: 'main-project-flask'
    build:
      context: .
      dockerfile: docker/python/Dockerfile
#    command: "python main.py"
    volumes:
      - ./server:/srv
#    ports:
#      - 8000:5000
    expose:
      - 5000
    depends_on:
      - db
    networks:
      - network

  db:
    container_name: 'main-project-db'
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - .database:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - network

  phpmyadmin:
    container_name: 'main-project-phpmyadmin'
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=main-project-db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    ports:
      - 8080:80
    networks:
      - network

networks:
  network:
